server:
  port: 8080

countries:
  api:
    base: https://restcountries.com/v3.1/
    density:
      fields: cca3,population,area
    borders:
      fields: cca3,borders,region

logging:
  level:
    org.springframework.web.servlet.PageNotFound: ERROR

spring:
  profiles:
    active: test